### PR TITLE
Merge pull request #13 from daytonlowell/fix-camel-case-keys

### LINKED ISSUE #5: Doesn't work on recent versions of MySQL due to uppercase columns in response
Win 10
node v10.15.1
database: cloud mysql

I can get table information via this snippet
```
const table_name = "users"
const sql = `desc ${table_name}`;
con.query(sql, function (err, resuts) {
  if (err) throw err;
  console.log(resuts);
  con.end();
});
```

But joi- sql returns:

```
Joi.object({
        undefined: Joi,
        undefined: Joi,
        undefined: Joi,
        undefined: Joi,
        undefined: Joi
})
```

I used joi-sql via this snippet with/without **connection: con** parameter
```
const con = mysql.createConnection({
  host: '***********',
  user: '*******',
  password: '************',
  database: '**********'
});


joiSql({
  host: '**********************',
  user: '*******',
  password: '********',
  schema: '*********',
  table: '****',
  camel: false,
  connection: con
}).then(result => {
  // typeof result // => 'string'
  console.log(result);
})
```

### PR DESCRIPTION
**Pull request by daytonlowell**
We shouldn't need to add anything to test data since the keys are already camel cased by the time they get passed into `build()`.

Fixes #5

### CODE REVIEW

File: fetch.js [hunk 1]
```diff
@@ -1,21 +1,31 @@
...
+	`CHARACTER_MAXIMUM_LENGTH`,
+	`IS_NULLABLE`,
+]
 
 module.exports = (db, { schema, table }) => {
 	return new Promise((resolve, reject) => {
-		let query = q.select(`column_name`, `data_type`, `column_type`, `numeric_precision`, `numeric_scale`, `character_maximum_length`, `is_nullable`)
-			.from(`information_schema.columns`)
-			.where(`table_schema`, schema)
+		let query = q.select(columns)
```
Comment (TehShrike) [inline fetch.js]: I think this needs to be `...columns`?  q.select expects any number of string arguments, not an array

File: fetch.js [hunk 2]
```diff
@@ -1,21 +1,31 @@
 const q = require(`sql-concat`)
-const camelize = require(`camelize`)
+const camelcaseKeys = require(`camelcase-keys`)
+
+const columns = [
```
Comment (TehShrike) [inline fetch.js]: I'd lean towards naming this `informationSchemaColumns` just to avoid the collision with that other `columns` variable on line 24

**Review by TehShrike — CHANGES_REQUESTED** [review]
Looks pretty sensible to me

**Review by TehShrike — APPROVED** [review]
